# Hombrew
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS="--require-sha --appdir=~/Applications"

# Path Updates
export GOPATH=${ZDOTDIR:-$HOME}/.go
export PATH=${ASDF_DATA_DIR:-$HOME/.asdf}/shims:${ZDOTDIR:-$HOME}/.local/bin:$GOPATH/bin:${ZDOTDIR:-$HOME}/.cargo/bin:/opt/homebrew/bin:$PATH

# AWS Vault
export AWS_VAULT_PROMPT=osascript
export AWS_VAULT_KEYCHAIN_NAME=login

# Git
export GIT_COMPLETION_CHECKOUT_NO_GUESS=1

# Python
export PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I/opt/homebrew/Cellar/tcl-tk/8.6.15/include' --with-tcltk-libs='-L/opt/homebrew/Cellar/tcl-tk/8.6.15/lib -ltcl8.6 -ltk8.6'"

# Editor
export VISUAL=nvim
export EDITOR=$VISUAL

# X11
export DISPLAY=:0

# Alias
alias whatsmyip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ls='lsd'
alias vim="nvim"
alias vi="nvim"

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

. /opt/homebrew/opt/asdf/libexec/asdf.sh
source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
